### ISSUE TITLE
When using go modules, the latest tag enters a segmetation fult in clients.go

### ISSUE THREAD

**Issue by egroj97** [theojulienne/go-wireless#15]
Hello,

I've been using your package over the last couple of days, but when moving to `go modules` I encountered an error constantly, a segmentation fault. 

After running my debugger on it, I found out that it happens because on your latest release you create a new client in the following manner:

```
// NewClient will create a new client by connecting to the
// given interface in WPA
func NewClient(iface string) (c *Client, err error) {
	c.conn, err = Dial(iface)
	if err != nil {
		return
	}

	return
}
```

From what I can see in master, that is already fixed, and those clients are created:
```
// NewClient will create a new client by connecting to the
// given interface in WPA
func NewClient(iface string) (c *Client, err error) {
	c = new(Client)
	c.conn, err = Dial(iface)
	if err != nil {
		return
	}

	return
}

```

Do you have plans to create another minor release in the future?

**Comment by tvanriper** [comment]
I tried to get around this with:

```golang
conn, err := wireless.Dial("wlan0")
if err != nil {
  fmt.Printf("failed to dial network: %s\n", err)
  os.Exit(1)
}
wc := wireless.NewClientFromConn(conn)
defer wc.Close()
```

but  it crashes on 'NewClientFromConn' because *that* code also does the empty return thing.  And because a client requires assigning the connection to a private variable, you can't get around NewClientFromConn.

**Comment by penguinpowernz** [comment]
Hi @egroj97 thanks for the bug report and sorry for the delay. I pushed a new tag v1.1.0, it includes some pull requests from other contributors, please let me know if it fixes your issue.

**Comment by penguinpowernz** [comment]
Assuming fixed
