### ISSUE TITLE
listen go routine doesn't close caused a high CPU usage issue

### ISSUE THREAD

**Issue by asymfermion** [theojulienne/go-wireless#16]
There is a listen go routine in conn.go, it won't be closed after the connection is closed. It should be closed. Otherwise, the go routine will continue running if you process is still running.

**Comment by penguinpowernz** [comment]
Need to pass a context to this, so it can be cancelled: https://github.com/theojulienne/go-wireless/blob/master/conn.go#L119

```golang
go c.listen()
```

**Comment by penguinpowernz** [comment]
Actually the quitchan you put in with #17 works well enough.
