### ISSUE TITLE
Connection listen buffer is not large enough for some WiFi environments

### ISSUE THREAD

**Issue by ahollist** [theojulienne/go-wireless#18]
When using this library, I experienced transient ocurrences of this error:
```record on line 30: wrong number of fields```

Initially I thought this was due to networks showing up in the scan results like this:
```f2:76:8f:71:41:af 2437 -81 [WPA2-PSK-CCMP][ESS]  ```
with no SSID, but I found that the tests were able to correctly parse those networks when I added this network into the `scanResults` 
https://github.com/theojulienne/go-wireless/blob/master/util_test.go#L77-L81

and I also noticed that when I set the `r.FieldsPerRecord` to `-1` and added in 
```golang
if len(rec) != 5 {
	continue
}
``` 
on https://github.com/theojulienne/go-wireless/blob/master/util.go#L75, I was getting more incomplete results than I expected.

I added in a wrapper around the error returned from `r.ReadAll()` in util.go on line 68, printing the full string that was being parsed by  `parseAP`, and found that the list did not match the `scan_results` given by `wpa_cli` on my host. The list was truncated to approximately 2048 characters (minus the first line which meant the resulting string was 2001 characters), which led me to look through the `Conn` struct, where I found that the `listen()` method had a buffer of 2048 bytes for reading from the connection.

In current WiFi environments, especially considering high-rises with many floors, it is common to have a very long list of WiFi networks in range seen by the wpa_supplicant scan, so I propose raising the listen buffer to 3072 (still well within Unix socket maximums) and wrapping the error given by `r.ReadAll()` in parseAP and parseNetwork to indicate the list being parsed might be too long.

**Comment by penguinpowernz** [comment]
Fixed.
